# Import  libraries

In [19]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
from datetime import timedelta

In [20]:
def Dataloader(CsvFile, ChunkSize, ChunkOverlap, OperationList)

#load in csv file
    df = pd.read_csv(CsvFile)

    chunks = [df[i:i+ChunkSize] for i in range(0,df.shape[0],ChunkOverlap)]

    frames = []

    for chunk in chunks:
        chunk = chunk.drop(columns=['Unnamed: 0'])
        frames.append(chunk)

        
    df_end =[]
    
    for frame in frames:
        if len(frame) == 100:
            result = [] #Reset the result array
            for column in list(frame.columns):
        
                if column in OperationList: #Check if column is in namelist
            
                    if OperationList[str(column)].values == 'cal.mean': #You can at more function if you want
                        X = cal.mean(frame[str(column)].tolist()) #Calculate mean of all columns named in namelist with operation cal.mean
            
                    else: #If the given operations isn't cal.mean
                        frame[str(column)] = [abs(ele) for ele in frame[str(column)]] #Get absolute value of all elements in list
                        X = max(frame[str(column)].tolist()) #Get single max value from list 
       
                else:
                    frame[str(column)] = [abs(ele) for ele in frame[str(column)]] #Get absolute value of all elements in list
                    X = max(frame[str(column)].tolist()) #Get single max value from list
            
                result.append(X) #Append results to list
        
            df_end.append(result) #Append all results into one big list
    
    df_end = pd.DataFrame(df_end, columns = list(frame.columns)) #Convert list to df
    return(df_end)

In [21]:
OperationList = [{ 'wheelRotationalSpeedX' : ['Cal.mean']}]
df_qs = pd.read_csv('Player_15_Game2_Sprints_Q234.csv')
df_qs

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,frAcc,frRoAcc,frDispl,frRoAng,frSpeed,timeLine,frameRotationalSpeedX,frameRotationalSpeedY,frameRotationalSpeedZ,wheelRotationalSpeedX,wheelRotationalSpeedY,wheelRotationalSpeedZ,frRoSpeed,Filt_WheelX,Filt_FrameZ,Action,Quarter
0,0,0,0,19.69000,2828.9,3410.8,228.56000,0.935400,3582.0,17.570,19.7400,228.7000,84.7310,193.7800,108.4800,2456.100,67.674366,204.464236,0.0,1
1,1,1,1,22.80600,2828.8,3391.0,228.56000,1.196400,3582.5,18.984,19.7400,228.7000,113.6100,193.7800,108.4800,2456.100,77.254375,204.540434,0.0,1
2,2,2,2,22.80600,2828.5,3313.6,106.98000,1.196400,3583.0,18.984,8.3300,107.7900,159.6700,92.5400,55.6290,1530.100,112.519339,204.540434,0.0,1
3,3,3,3,13.70100,2829.1,3280.3,86.24200,1.960100,3583.5,17.472,7.9100,85.2600,288.6700,73.2430,55.6290,1530.100,143.311081,60.639928,0.0,1
4,4,4,4,14.08900,2829.9,3289.0,89.03700,2.054900,3584.0,17.472,7.5200,87.8500,410.7800,88.9700,33.1100,1006.200,266.441224,60.511982,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9054,9054,9054,9054,0.70001,6556.8,1948.5,6.78380,0.072376,8602.0,2.380,1.5867,7.3220,5.6544,6.6500,5.1800,54.922,4.586872,8.607160,0.0,4
9055,9055,9055,9055,0.40442,6556.8,1948.4,6.78380,0.053704,8602.5,1.820,1.0920,5.8800,5.4600,4.1922,2.1000,65.299,4.392796,5.850487,0.0,4
9056,9056,9056,9056,0.36332,6556.8,1946.9,6.16700,0.053550,8603.0,1.820,1.0422,5.2640,5.4600,4.1922,2.1467,65.299,4.418443,3.237448,0.0,4
9057,9057,9057,9057,0.17616,6556.8,1946.7,0.74254,0.009661,8603.5,1.470,1.0422,1.3222,2.4500,2.1700,2.1467,21.614,4.418443,2.107930,0.0,4
9058,9058,9058,9058,0.12284,6556.8,1946.6,0.37909,0.002951,8604.0,1.260,1.0360,1.2600,1.6660,1.5789,1.7500,13.551,2.188870,1.195376,0.0,4

In [22]:
df_RNN = pd.read_csv('Predictions_15x2_Quartor1_Overlap.csv')
df_RF = pd.read_csv('Sprint_results_randomforest_Q1.csv')

In [23]:
df_RNN = df_RNN.drop(columns=['Unnamed: 0'])
df_RF = df_RF.drop(columns=['Unnamed: 0'])

In [24]:
df = pd.concat([df_RF, df_RNN], axis=1)

In [25]:
df = df[['timeLine','Action','0']]

In [26]:
df = df.fillna(0)
df['0'] = df['0'].astype(int)
df['Action'] = df['Action'].astype(int)
df = df.rename(columns={'Action':'Action_RF', '0':'Action_RNN'})

In [27]:
df = df[(df['Action_RF'] == df['Action_RNN'])]
df = df[df['Action_RF'] == 1]

In [28]:
df

      timeLine  Action_RF  Action_RNN
9       3586.5          1           1
10      3587.0          1           1
11      3587.5          1           1
20      3592.0          1           1
21      3592.5          1           1
...        ...        ...         ...
1523    4343.5          1           1
1524    4344.0          1           1
1526    4345.0          1           1
1527    4345.5          1           1
1532    4348.0          1           1

[383 rows x 3 columns]

In [29]:
df_check = df

In [30]:
#df_qs = df_qs.drop(columns=['Unnamed: 0'])
print(df_qs.loc[df_qs.timeLine == 4020.5])

     Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1   frAcc  frRoAcc  frDispl  \
877         877           877             877  9.7728   3301.7   3042.2

     frRoAng  frSpeed  timeLine  frameRotationalSpeedX  frameRotationalSpeedY  \
877    14.96   2.9817    4020.5                 8.5011                  3.577

     frameRotationalSpeedZ  wheelRotationalSpeedX  wheelRotationalSpeedY  \
877                 15.781                 536.83                 43.003

     wheelRotationalSpeedZ  frRoSpeed  Filt_WheelX  Filt_FrameZ  Action  \
877                 44.898     158.96   531.033853    12.602682     0.0

     Quarter
877        1

In [31]:
Check = df_check.timeLine.to_numpy()

In [32]:
Check

array([3586.5, 3587. , 3587.5, 3592. , 3592.5, 3598.5, 3599. , 3600.5,
       3601. , 3601.5, 3602. , 3602.5, 3603. , 3603.5, 3604. , 3604.5,
       3605. , 3605.5, 3606.5, 3609. , 3609.5, 3610. , 3615.5, 3624.5,
       3625. , 3625.5, 3626. , 3636.5, 3637. , 3637.5, 3638.5, 3639. ,
       3640.5, 3641. , 3641.5, 3642. , 3642.5, 3643. , 3643.5, 3649. ,
       3649.5, 3654.5, 3655. , 3655.5, 3656. , 3656.5, 3657. , 3657.5,
       3658. , 3658.5, 3659. , 3659.5, 3660. , 3660.5, 3671. , 3671.5,
       3672. , 3672.5, 3673. , 3673.5, 3674. , 3674.5, 3675. , 3675.5,
       3692.5, 3693. , 3694. , 3694.5, 3695. , 3695.5, 3696.5, 3727. ,
       3727.5, 3728. , 3729.5, 3730. , 3730.5, 3731. , 3731.5, 3732. ,
       3732.5, 3733. , 3733.5, 3734. , 3734.5, 3735. , 3736. , 3736.5,
       3737. , 3737.5, 3762.5, 3763. , 3768. , 3768.5, 3769. , 3769.5,
       3770. , 3770.5, 3771. , 3771.5, 3772. , 3772.5, 3773. , 3773.5,
       3774. , 3774.5, 3780. , 3798.5, 3799. , 3799.5, 3800. , 3800.5,
       3801. , 3801.5, 3802. , 3802.5, 3803. , 3803.5, 3804. , 3810.5,
       3811. , 3811.5, 3812.5, 3813. , 3813.5, 3814. , 3814.5, 3815. ,
       3815.5, 3816. , 3838. , 3838.5, 3839. , 3839.5, 3840.5, 3841. ,
       3849. , 3852. , 3852.5, 3853. , 3853.5, 3854. , 3854.5, 3855. ,
       3855.5, 3856. , 3856.5, 3857. , 3950.5, 3951. , 3951.5, 3952. ,
       3952.5, 3953. , 3953.5, 3954. , 3957. , 3957.5, 3958. , 3958.5,
       3959.5, 3960. , 3960.5, 3961. , 3961.5, 3962. , 3964. , 3965. ,
       3965.5, 3969.5, 3970. , 3970.5, 3971. , 3971.5, 3972. , 3972.5,
       3973. , 3973.5, 3978.5, 3997. , 4002.5, 4003. , 4014.5, 4015. ,
       4015.5, 4016. , 4016.5, 4017. , 4017.5, 4018. , 4018.5, 4019. ,
       4019.5, 4020. , 4020.5, 4021. , 4021.5, 4022. , 4022.5, 4023. ,
       4023.5, 4024. , 4033. , 4033.5, 4035. , 4035.5, 4036. , 4036.5,
       4037. , 4037.5, 4038. , 4038.5, 4039. , 4039.5, 4040. , 4040.5,
       4041. , 4041.5, 4042. , 4042.5, 4048. , 4048.5, 4049. , 4054. ,
       4054.5, 4055. , 4055.5, 4056. , 4056.5, 4057.5, 4058. , 4058.5,
       4059. , 4059.5, 4060. , 4060.5, 4061. , 4061.5, 4062. , 4064.5,
       4070.5, 4106.5, 4107. , 4107.5, 4108. , 4108.5, 4109. , 4109.5,
       4110. , 4110.5, 4111. , 4111.5, 4112. , 4112.5, 4113. , 4113.5,
       4114. , 4114.5, 4115. , 4115.5, 4118. , 4119. , 4119.5, 4120. ,
       4120.5, 4121. , 4122.5, 4123. , 4123.5, 4124. , 4124.5, 4125. ,
       4125.5, 4126. , 4126.5, 4160.5, 4163. , 4167. , 4167.5, 4169. ,
       4169.5, 4170. , 4170.5, 4171. , 4171.5, 4172. , 4172.5, 4173. ,
       4177.5, 4186.5, 4190. , 4190.5, 4191. , 4191.5, 4192. , 4192.5,
       4193. , 4193.5, 4194. , 4194.5, 4195.5, 4196. , 4196.5, 4197. ,
       4199. , 4199.5, 4201.5, 4205. , 4206.5, 4207.5, 4217. , 4217.5,
       4218. , 4218.5, 4219. , 4219.5, 4220. , 4220.5, 4221. , 4224.5,
       4225. , 4225.5, 4250. , 4260. , 4260.5, 4261. , 4261.5, 4268. ,
       4268.5, 4269. , 4282. , 4282.5, 4283. , 4284.5, 4285. , 4287. ,
       4287.5, 4288. , 4288.5, 4289. , 4289.5, 4290. , 4290.5, 4291. ,
       4291.5, 4292. , 4293. , 4297.5, 4304. , 4304.5, 4305. , 4306. ,
       4306.5, 4307. , 4307.5, 4308. , 4308.5, 4309.5, 4310. , 4310.5,
       4311. , 4311.5, 4312. , 4320. , 4320.5, 4321.5, 4322.5, 4323. ,
       4323.5, 4324. , 4324.5, 4325. , 4328. , 4328.5, 4341.5, 4342. ,
       4342.5, 4343. , 4343.5, 4344. , 4345. , 4345.5, 4348. ])

In [33]:
for time in Check:
    df_qs.loc[df_qs['timeLine'] == time, 'Action'] = 1

In [34]:
print(df_qs.loc[df_qs.timeLine == 4020.5])

     Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1.1   frAcc  frRoAcc  frDispl  \
877         877           877             877  9.7728   3301.7   3042.2

     frRoAng  frSpeed  timeLine  frameRotationalSpeedX  frameRotationalSpeedY  \
877    14.96   2.9817    4020.5                 8.5011                  3.577

     frameRotationalSpeedZ  wheelRotationalSpeedX  wheelRotationalSpeedY  \
877                 15.781                 536.83                 43.003

     wheelRotationalSpeedZ  frRoSpeed  Filt_WheelX  Filt_FrameZ  Action  \
877                 44.898     158.96   531.033853    12.602682     1.0

     Quarter
877        1

In [35]:
df_qs

,Unnamed: 0,Unnamed: 0.1,Unnamed: 0.1.1,frAcc,frRoAcc,frDispl,frRoAng,frSpeed,timeLine,frameRotationalSpeedX,frameRotationalSpeedY,frameRotationalSpeedZ,wheelRotationalSpeedX,wheelRotationalSpeedY,wheelRotationalSpeedZ,frRoSpeed,Filt_WheelX,Filt_FrameZ,Action,Quarter
0,0,0,0,19.69000,2828.9,3410.8,228.56000,0.935400,3582.0,17.570,19.7400,228.7000,84.7310,193.7800,108.4800,2456.100,67.674366,204.464236,0.0,1
1,1,1,1,22.80600,2828.8,3391.0,228.56000,1.196400,3582.5,18.984,19.7400,228.7000,113.6100,193.7800,108.4800,2456.100,77.254375,204.540434,0.0,1
2,2,2,2,22.80600,2828.5,3313.6,106.98000,1.196400,3583.0,18.984,8.3300,107.7900,159.6700,92.5400,55.6290,1530.100,112.519339,204.540434,0.0,1
3,3,3,3,13.70100,2829.1,3280.3,86.24200,1.960100,3583.5,17.472,7.9100,85.2600,288.6700,73.2430,55.6290,1530.100,143.311081,60.639928,0.0,1
4,4,4,4,14.08900,2829.9,3289.0,89.03700,2.054900,3584.0,17.472,7.5200,87.8500,410.7800,88.9700,33.1100,1006.200,266.441224,60.511982,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9054,9054,9054,9054,0.70001,6556.8,1948.5,6.78380,0.072376,8602.0,2.380,1.5867,7.3220,5.6544,6.6500,5.1800,54.922,4.586872,8.607160,0.0,4
9055,9055,9055,9055,0.40442,6556.8,1948.4,6.78380,0.053704,8602.5,1.820,1.0920,5.8800,5.4600,4.1922,2.1000,65.299,4.392796,5.850487,0.0,4
9056,9056,9056,9056,0.36332,6556.8,1946.9,6.16700,0.053550,8603.0,1.820,1.0422,5.2640,5.4600,4.1922,2.1467,65.299,4.418443,3.237448,0.0,4
9057,9057,9057,9057,0.17616,6556.8,1946.7,0.74254,0.009661,8603.5,1.470,1.0422,1.3222,2.4500,2.1700,2.1467,21.614,4.418443,2.107930,0.0,4
9058,9058,9058,9058,0.12284,6556.8,1946.6,0.37909,0.002951,8604.0,1.260,1.0360,1.2600,1.6660,1.5789,1.7500,13.551,2.188870,1.195376,0.0,4

In [37]:
df_qs.to_csv('Player_15_Game2_Sprints_Q1234.csv')